version: 0.2
env:
  shell: bash
  exported-variables:
    - PACKAGE_BUILD_HASH
    - PACKAGE_KEY
phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    on-failure: ABORT
    commands:
      - 'cd "${CODEBUILD_SRC_DIR}/${PROJECT_SUBDIR}"'
      - 'make test'
      - 'make dist'
  post_build:
    on-failure: ABORT
    commands:
      - 'cd "${CODEBUILD_SRC_DIR}/${PROJECT_SUBDIR}"'
      - |
        if [[ -n $PACKAGE_BUCKET && -n $PACKAGE_PREFIX && -n $ENVIRONMENT ]]; then
          PACKAGE_BUILD_HASH=$(find build/ -type f -exec md5sum {} + | LC_ALL=C sort | md5sum | cut -d' ' -f1)
          PACKAGE_KEY="${PACKAGE_PREFIX}${PACKAGE_BUILD_HASH}.zip"
          aws s3 cp dist/dynamodbStreamEvents.zip s3://${PACKAGE_BUCKET}/${PACKAGE_KEY}
        fi
artifacts:
  files:
    - dist/dynamodbStreamEvents.zip
  base-directory: $CODEBUILD_SRC_DIR/$PROJECT_SUBDIR
  discard-paths: yes
cache:
  paths:
    - $CODEBUILD_SRC_DIR/$PROJECT_SUBDIR/.venv
