version: 0.2
env:
  shell: bash
  variables:
    APP_NAME: dynamodbStreamEvents
phases:
  install:
    runtime-versions:
      python: 3.11
  build:
    on-failure: ABORT
    commands:
      - 'cd "${CODEBUILD_SRC_DIR}/${PROJECT_SUBDIR}"'
      - 'make lint-report || :'
      - 'make test-report'
      - 'make build'
  post_build:
    on-failure: ABORT
    commands:
      - 'cd "${CODEBUILD_SRC_DIR}/${PROJECT_SUBDIR}"'
      - |
        if [[ -n $PACKAGE_BUCKET || $PACKAGE_COUNT -gt 0 ]]; then
          make package
        fi
rtifacts:
  files:
    - $APP_NAME.zip
  base-directory: $CODEBUILD_SRC_DIR/$PROJECT_SUBDIR/dist/
  discard-paths: yes
reports:
  pylint:
    files:
      - pylint.xml
    base-directory: $CODEBUILD_SRC_DIR/$PROJECT_SUBDIR/reports/
    file-format: JUNITXML
  pytest:
    files:
      - pytest.xml
    base-directory: $CODEBUILD_SRC_DIR/$PROJECT_SUBDIR/reports/
    file-format: JUNITXML
cache:
  paths:
    - $CODEBUILD_SRC_DIR/$PROJECT_SUBDIR/.venv
