version: 0.2
env:
  shell: bash
  exported-variables:
    - PACKAGE_BUILD_HASH
    - PACKAGE_KEY
phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    on-failure: ABORT
    commands:
      - 'cd "${CODEBUILD_SRC_DIR}/${PROJECT_SUBDIR}"'
      - 'make lint-report || :'
      - 'make test-report'
      - 'make dist'
  post_build:
    on-failure: ABORT
    commands:
      - 'cd "${CODEBUILD_SRC_DIR}/${PROJECT_SUBDIR}"'
      - |
        if [[ $PACKAGE_COUNT -gt 0 && -n $ENVIRONMENT ]]; then
          PACKAGE_BUILD_HASH=$(find build/ -type f -exec md5sum {} + | LC_ALL=C sort | md5sum | cut -d' ' -f1)
          PACKAGE_KEY="${PACKAGE_PREFIX}dynamodbStreamEvents/${PACKAGE_BUILD_HASH}.zip"

          for idx in $(seq 0 $PACKAGE_COUNT); do
            bucket=PACKAGE_${idx}_BUCKET
            key_id=PACKAGE_${idx}_KMS_KEY_ID

            [[ -n ${!bucket} ]] || continue
            aws s3 cp dist/dynamodbStreamEvents.zip s3://${!bucket}/${PACKAGE_KEY} --sse aws:kms --sse-kms-key-id ${!key_id:-alias/aws/s3}
            aws s3 cp dist/dynamodbStreamEvents.zip s3://${!bucket}/${PACKAGE_PREFIX}dynamodbStreamEvents/${ENVIRONMENT}.zip --sse aws:kms --sse-kms-key-id ${!key_id:-alias/aws/s3}
          done
        fi
artifacts:
  files:
    - dist/dynamodbStreamEvents.zip
  base-directory: $CODEBUILD_SRC_DIR/$PROJECT_SUBDIR
  discard-paths: yes
reports:
  pylint:
    files:
      - pylint.xml
    base-directory: $CODEBUILD_SRC_DIR/$PROJECT_SUBDIR/reports/
    file-format: JUNITXML
  pytest:
    files:
      - pytest.xml
    base-directory: $CODEBUILD_SRC_DIR/$PROJECT_SUBDIR/reports/
    file-format: JUNITXML
cache:
  paths:
    - $CODEBUILD_SRC_DIR/$PROJECT_SUBDIR/.venv
